// <auto-generated />
namespace kpi_peformance.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class kpimigrationdatabase : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(kpimigrationdatabase));
        
        string IMigrationMetadata.Id
        {
            get { return "202406200414297_kpi migration database"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
